### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by ordago**

### CODE REVIEW

**Review by GeniusGeeek — CHANGES_REQUESTED** [review]
Thanks Ordago your commit is very valid, please check that you update  function's argument to updated variables you used in puconverter.php which are $value, $fromUnit, and $toUnit on the More examples section in README.md so your commit will be approved and merged, thanks. Hoping to see your upcoming contributions too:)

**Comment by ordago** [comment]
@GeniusGeeek 
Renamed the variables in the examples in the new commit.

**Comment by GeniusGeeek** [comment]
Noted

**Review by GeniusGeeek — APPROVED** [review]

**Comment by GeniusGeeek** [comment]
Thanks for your valid contribution

**Pull request merged**
